### ISSUE TITLE
Non-functional for Oxford Dictionary?

### ISSUE THREAD

**Issue by AlexBlandin** [Rican7/define#15]
Currently getting (for any input)
```cmd
> define Oxford

  The source returned an empty result for word: "Oxford"


> define --print-config
{
    "IndentationSize": 2,
    "MerriamWebsterDictionary": {
        "AppKey": ""
    },
    "OxfordDictionary": {
        "AppID": "########",
        "AppKey": "###############################"
    },
    "PreferredSource": "OxfordDictionary",
    "Source": "OxfordDictionary"
}

> define --version
define v0.1.2 (windows/amd64)
```
Censored ID/key but they are correct. Remains the same even if I don't have the source set (as default with `"Source": ""`). ID/key are set and correct for both config and envar.

**Comment by Rican7** [comment]
Yeaaaa, the Oxford API was updated and they dropped support for v1. See #12.

I need to get to reviewing #13 soon, which _should_ fix this.

Sorry!
