### ISSUE TITLE
Quotes Are Unescaped And Left As HTML Number

### ISSUE THREAD

**Issue by jshah** [Rican7/define#5]
Example:

```➜  define git:(master) define benevolent

  benevolent

    1. altruistic or charitable.
    2. generous.
    3. altruistic, charitable, good, just and fair.
    4. Having a disposition to do good
    5. generous in providing aid to others
    6. showing or motivated by sympathy and understanding and generosity; &#34;was charitable in his opinions of others&#34;; &#34;kindly criticism&#34;; &#34;a kindly act&#34;; &#34;sympathetic words&#34;; &#34;a large-hearted mentor&#34;
    7. Possessing or manifesting love for mankind.
    8. Possessing or manifesting love for mankind
    9. intending or showing kindness; &#34;a benevolent society&#34;
    10. Having a disposition to do good.
    11. altruistic or charitable
    12. generous in assistance to the poor; &#34;a benevolent contributor&#34;; &#34;eleemosynary relief&#34;; &#34;philanthropic contributions&#34;


  ---------------------------------
  Results provided by: "Glosbe API"
```

I believe all you have to do is unescape the text during writing.

**Comment by jshah** [comment]
I am interested in contributing this change, assigning issue to myself.

**Comment by jshah** [comment]
I am interested in contributing this change, could you assign this issue to me @Rican7

**Comment by Rican7** [comment]
@jshah Good find on the bug! I would absolutely love to receive a contribution. Feel free to open a pull request. 😃

**Comment by jshah** [comment]
@Rican7 I'm trying to push a branch but I am unable to, have you disabled access externally somehow? Not sure what the issue is here, I'm able to push to other repos.

```
remote: Permission to Rican7/define.git denied to jshah.
fatal: unable to access 'https://github.com/Rican7/define.git/': The requested URL returned error: 403
```

**Comment by jshah** [comment]
@Rican7 have you had a chance to look? still unable to push to this repo.

**Comment by Rican7** [comment]
@jshah You shouldn't be able to push to my repo unless I explicitly make you a co-owner, which is just unnecessary. The fork and PR model is the preferred model of contribution on GitHub:
https://guides.github.com/activities/forking/
